"use client";

import "./globals.css";
import { useRef } from "react";
import { Provider } from "react-redux";
import { makeStore } from "@/lib/redux/store";
import type { AppStore } from "@/lib/redux/store";
import { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner";

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Cria a store uma única vez durante a renderização inicial
  const storeRef = useRef<AppStore | null>(null);
  if (!storeRef.current) {
    storeRef.current = makeStore();
  }

  return (
    <html lang="pt-BR">
      <body>
        <Provider store={storeRef.current}>{children}</Provider>
        <Toaster />
      </body>
    </html>
  );
}
